[env:node32s]
platform = espressif32
board = node32s
framework = espidf
lib_deps = codewitch-honey-crisis/htcw_ws565f
upload_speed = 921600
monitor_speed = 115200
monitor_filters=esp32_exception_decoder
